### ISSUE TITLE
Issueing 'usb start' while some USB device is connected --> device hang

### ISSUE THREAD

**Issue by ingmar-k** [kref/u-boot-oxnas#1]
Hi kref,

first of all, thank you very much for your efforts in porting OX820 support to a recent U-Boot version.
It is highly appreciated!

Thanks to your hints I could successfully build a NAND version and flash it to my Pogoplug V3 (B04). 
I noticed one problem however, concerning the USB functionality.

How to reproduce the problem:
- Start the Plug and stop U-Boot at the input prompt.
- Issue a 'usb start' to make it scan the USB bus (while no USB device is connected!).
- Everything is fine. Scan runs, find's no devices and the Pogoplug is still reacting to new commands.
- Now connect a USB thumb drive and repeat the same.
- This time, the Pogoplug will freeze completely while attempting to scan the bus.
- If the usb functionality was already started with 'usb start' before inserting the USB device, the Pogoplug will freeze completely, immediately upon inserting the connector into the USB plug.

I know that the USB functionality is more or less just icing on the cake.
Nevertheless, it would be great if you maybe could find a fix for this. ;-)

Have a nice day and thank you very much in advance!

Regards

Ingmar

**Comment by kref** [comment]
I am unable to reproduce this issue on a pogoplug video.  Maybe this is related to some clock problem, so comment the line "#define CONFIG_USB_PLLB_CLK"  in include/configs/ox820.h, see if it helps.

```
U-Boot 2013.07-00032-g8cefee1 (Nov 16 2013 - 13:51:43) for OXNAS

DRAM:  128 MiB
NAND:  128 MiB
In:    serial
Out:   serial
Err:   serial
Net:   mii0
Hit any key to stop autoboot:  0 
OX820 # usb start
(Re)start USB...
USB0:   USB EHCI 1.00
scanning bus 0 for devices... 2 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found
OX820 # usb tree
USB device tree:
  1  Hub (480 Mb/s, 0mA)
  |  u-boot EHCI Host Controller 
  |
  +-2  Hub (480 Mb/s, 100mA)
        USB2.0 Hub 

OX820 # usb start
(Re)start USB...
USB0:   USB EHCI 1.00
scanning bus 0 for devices... 3 USB Device(s) found
       scanning usb for storage devices... 1 Storage Device(s) found
OX820 # usb tree
USB device tree:
  1  Hub (480 Mb/s, 0mA)
  |  u-boot EHCI Host Controller 
  |
  +-2  Hub (480 Mb/s, 100mA)
    |   USB2.0 Hub 
    |
    +-3  Mass Storage (480 Mb/s, 500mA)
         General                        USB Flash Disk                 0000000000000E4F

OX820 # 
```

**Comment by ingmar-k** [comment]
OK, forget the USB problem!
I had the Plug powered by an external 5V power supply, because I was only running the bare disassembled PCB outside the case.
Somehow that external power supply led to the USB problems. Maybe too serious fluctuations on the 5V output, I don't know.
Anyway, just before trying your potential fix, I realized that I maybe should try again with the stock power supply. Bam, USB is working like it should. So, sorry about that!
The realization that the Plug is pretty sensitive to its 5V input however could be a interesting fact.

The power consumption "problem" however, persists. Will have to do some tests there, with enabling and disabling certain parts and doing further tests then.
